[project]
name = "skland-api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "requests>=2.32.3",
]

[project.scripts]
skland = "skland_api.cli:main"

[project.optional-dependencies]
cli = [
    "platformdirs>=4.3.8",
    "wcwidth>=0.2.13",
]
interactive = [
    "platformdirs>=4.3.8",
    "prompt-toolkit>=3.0.51",
]

[build-system]
requires = ["uv_build>=0.7.8,<0.8.0"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-root = ""

